server:
  port: 8082

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/campusflow_requests}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

gcp:
  project-id: ${GCP_PROJECT_ID:campusflow-eca-2026}
  storage:
    bucket-name: ${GCS_BUCKET_NAME:campusflow-attachments-eca-2026}

jwt:
  secret: ${JWT_SECRET:campusflow-local-dev-secret-key-that-is-at-least-256-bits-long}
